version: "3"
services:
  maple:
    image: maple:latest
    container_name: maple
    ports:
      - 8080:8080
    networks:
      - cirrusnetwork
  postgres:
    image: postgres:12.2
    volumes:
      - data:/var/lib/postgres/data
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: maple
    networks:
      - cirrusnetwork
    ports:
      - "35432:5432"
networks:
  cirrusnetwork:
    driver: bridge
volumes:
  data: {}